### ISSUE TITLE
Typographic error found by Joseph Mc Guire

### ISSUE THREAD

**Issue by rleduc42** [topdownproteomics/proteoform-nomenclature-standard#16]
Rule 6. Pre_x Tag
If all tags in a proteoform use the same Key, the sequence may be PREFIXED with a
single tag de_ning the Key followed by a plus sign.
e.g. [RESID]+SE[12]QUE[42]NCE
Here the numbers in brackets are accession numbers in the resid database e.g.
[mass]+SE[12]QUE[42]NCE
Here the numbers in brackets are masses e.g. [formula]+SE[CH(2)]QUE[H(2)O]NCE

**Comment by stefanks** [comment]
Does this solve the issue? 
https://github.com/topdownproteomics/proteoform-nomenclature-standard/pull/23
