### ISSUE TITLE
Add folders

### ISSUE THREAD

**Issue by veitveit** [topdownproteomics/proteoform-nomenclature-standard#4]
Folders for a) validator software and b) converters

**Comment by acesnik** [comment]
Just adding the image to GitHub via a closed issue.
[TOCGraphic2.pdf](https://github.com/topdownproteomics/ProteoformNomenclatureStandard/files/2833088/TOCGraphic2.pdf)

**Comment by acesnik** [comment]
![tocgraphic2](https://user-images.githubusercontent.com/16342951/52293228-36b9f580-292b-11e9-988d-e31e28e1f4b9.png)
